CREATE DATABASE IF NOT EXISTS cryptobird DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE cryptobird;

CREATE TABLE `USER` (
	`id` int NOT NULL AUTO_INCREMENT,
	`email` varchar(320) NOT NULL UNIQUE,
	`username` varchar(254) NOT NULL UNIQUE,
	`password` BINARY(60) NOT NULL,
	`createddate` DATETIME NOT NULL,
	`token` char(32) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `GROUP_MESSAGE` (
	`id` int NOT NULL AUTO_INCREMENT,
	`group` int NOT NULL,
	`sender` int NOT NULL,
	`content` TEXT NOT NULL,
	`datetime` DATETIME NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `GROUP` (
	`id` int NOT NULL AUTO_INCREMENT,
	`status` bit NOT NULL,
	`access` int(1) NOT NULL,
	PRIMARY KEY (`id`)
);

CREATE TABLE `USER_LINK` (
	`user` int NOT NULL,
	`group` int NOT NULL,
	`status` bit NOT NULL,
	`nickname` varchar(254) NOT NULL,
	PRIMARY KEY (`user`,`group`)
);

CREATE TABLE `CONTACT` (
	`user` int NOT NULL,
	`contact` int NOT NULL,
	`status` int(1) NOT NULL,
	PRIMARY KEY (`user`,`contact`)
);

CREATE TABLE `USER_MESSAGE` (
	`id` int NOT NULL AUTO_INCREMENT,
	`from` int NOT NULL,
	`to` int NOT NULL,
	`content` TEXT NOT NULL,
	`datetime` DATETIME NOT NULL,
	PRIMARY KEY (`id`)
);

ALTER TABLE `GROUP_MESSAGE` ADD CONSTRAINT `GROUP_MESSAGE_fk0` FOREIGN KEY (`group`) REFERENCES `GROUP`(`id`);

ALTER TABLE `GROUP_MESSAGE` ADD CONSTRAINT `GROUP_MESSAGE_fk1` FOREIGN KEY (`sender`) REFERENCES `USER`(`id`);

ALTER TABLE `USER_LINK` ADD CONSTRAINT `USER_LINK_fk0` FOREIGN KEY (`user`) REFERENCES `USER`(`id`);

ALTER TABLE `USER_LINK` ADD CONSTRAINT `USER_LINK_fk1` FOREIGN KEY (`group`) REFERENCES `GROUP`(`id`);

ALTER TABLE `CONTACT` ADD CONSTRAINT `CONTACT_fk0` FOREIGN KEY (`user`) REFERENCES `USER`(`id`);

ALTER TABLE `CONTACT` ADD CONSTRAINT `CONTACT_fk1` FOREIGN KEY (`contact`) REFERENCES `USER`(`id`);

ALTER TABLE `USER_MESSAGE` ADD CONSTRAINT `USER_MESSAGE_fk0` FOREIGN KEY (`from`) REFERENCES `USER`(`id`);

ALTER TABLE `USER_MESSAGE` ADD CONSTRAINT `USER_MESSAGE_fk1` FOREIGN KEY (`to`) REFERENCES `USER`(`id`);